version: '3.9'
services:
  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    env_file:
      - .env.dev
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql-data: