[settings]
os=Linux
arch=armv8
build_type=Debug
compiler=clang
compiler.version=14
compiler.libcxx=libstdc++11
compiler.cppstd=gnu20

[options]
boost/*:without_locale=True
boost/*:without_stacktrace=True

[conf]
tools.build:compiler_executables={"c":"clang","cpp":"clang++"}
tools.system.package_manager:mode=install

[buildenv]
CFLAGS=--target=aarch64-linux-gnu
CXXFLAGS=--target=aarch64-linux-gnu
LDFLAGS=--target=aarch64-linux-gnu
CC=clang
CXX=clang++
LD=aarch64-linux-gnu-ld
AR=aarch64-linux-gnu-ar
RANLIB=aarch64-linux-gnu-ranlib
NM=aarch64-linux-gnu-nm
STRIP=aarch64-linux-gnu-strip
OBJCOPY=aarch64-linux-gnu-objcopy
OBJDUMP=aarch64-linux-gnu-objdump