[settings]
os=Linux
arch=armv8
build_type=Debug
compiler=clang
compiler.version=14
compiler.libcxx=libstdc++11
compiler.cppstd=gnu20

[conf]
tools.build:compiler_executables={"c":"clang","cpp":"clang++"}
tools.system.package_manager:mode=install
