name: Build

on:
  push:
    branches:
      - feature/*

jobs:
  run-build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Deps and Build
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          conan install . --build=missing
          cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=Debug/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -G "Ninja"
          ninja
        # we don't need to push docker image that was built using our Dev Container
        push: never
