name: Build and push devcontainer image

on:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   paths:
  #     - "deps/*"
  #     - "conanfile.py"
  #     - ".devcontainer/Dockerfile"
  push:
    branches:
    - "feature/*"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    # - name: Log in to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
    # this is needed to address this issue according to the comment https://github.com/devcontainers/ci/issues/271#issuecomment-2301764487
    # otherwise our TourmalineCore org name cannot be used in docker image names, only tourmalinecore
    - name: Add DEV_CONTAINER_IMAGE Env Var with Lowercase Organization, Repo Name and devcontainer postfix
      run: |
        echo "DEV_CONTAINER_IMAGE=${GITHUB_REPOSITORY,,}-devcontainer" >>${GITHUB_ENV}
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.DEV_CONTAINER_IMAGE }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix=sha-
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        file: .devcontainer/Dockerfile
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ env.DEV_CONTAINER_IMAGE }}:latest
        cache-to: type=inline